### ISSUE TITLE
How to change the width of underline of links

### ISSUE THREAD

**Issue by binxiangni** [rbind/daijiang#2]
Hi, I'm new to blogdown and used some of your codes to modify some properties of the original theme. Thanks! But the green underline of links in the original theme is too wide and I cannot find how you modify it. Could you please give me a hint?

**Comment by daijiang** [comment]
You should decrease the value of this line https://github.com/rbind/daijiang/blob/master/static/css/custom.css#L60 to say, 0.5px

If it works, you can then close this issue. Thanks.
